"""Compile fixed cast-cancel windows; bindings and process addresses never seed them."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / 'runtime/native/cast_pulse_profiles.h'


def sources():
    # Paired attacks own another actor and cannot enter William's ordinary cast path.
    keys = ('key', 'motion', 'flags', 'transition_count', 'recovery_frame')
    moves = {tuple(move[key] for key in keys)
             for path in (ROOT / 'mwm/data/imports').glob('*.json')
             for move in json.loads(path.read_text(encoding='utf-8'))['moves']
             if move.get('adapter_kind') != 3 and move['flags'] not in (0x8078000000, 0x8038000000)}
    # Exact native Quick/Strong stages; rows=0 distinguishes these from imported signatures.
    for key, motion, count in ((0xCB3, 3100, 3), (0xCB7, 3300, 3),
                              (0xC76, 2100, 3), (0xC7A, 2300, 3),
                              (0xCF0, 4100, 5), (0xCF5, 4300, 3)):
        moves.update((key + step, motion + 10 * step, 0x8000000594C0000, 0, 0)
                     for step in range(count))
    return sorted(moves)


def score(source, purpose):
    identity = purpose + ':' + ','.join(map(str, source))
    return int.from_bytes(hashlib.sha256(identity.encode('ascii')).digest(), 'big')


def generate():
    moves = sources()
    # Rank the full shipped pool, not the selected preset; round quotas to whole phases.
    eligible = [set(sorted(moves, key=lambda move: score(move, kind))[:(len(moves) * percent + 50) // 100])
                for kind, percent in (('onmyo', 60), ('shuriken', 70))]
    lines = ['#pragma once', '#include <stdint.h>', '',
             '// Generated by tools/generate_cast_profiles.py. One profile per source phase; aliases share it.',
             '// Window frames follow effect release and remain bounded by the native sword Pulse deadline.',
             'struct CastPulseProfile {',
             '    uint32_t key; int32_t motion; uint64_t flags; uint16_t rows; int16_t recovery;',
             '    uint8_t delay, onmyo, shuriken;',
             '};', 'static constexpr CastPulseProfile cast_pulse_profiles[]={']
    for move in moves:
        key, motion, flags, rows, recovery = move
        random = score(move, 'timing')
        delay, width = 2 + random % 7, 5 + (random >> 8) % 6
        onmyo, shuriken = (width if move in group else 0 for group in eligible)
        lines.append(f'    {{0x{key:X},{motion},0x{flags:X}ULL,{rows},{recovery},{delay},{onmyo},{shuriken}}},')
    return '\n'.join(lines + ['};', ''])


if __name__ == '__main__':
    DESTINATION.write_text(generate(), encoding='utf-8')
    print(f'Wrote {DESTINATION} ({len(sources())} unique phases)')
